    ope-git:
        build: ./ope-git
        image: operepo/ope-git:release
        container_name: ope-git
        restart: always
        network_mode: <NETWORK_MODE>
        hostname: git.<DOMAIN>
        ports:
            - "80"
            #- "443"
            - "2224:2224"
            #- "8080"
        volumes:
            - ../volumes/git/config:/etc/git:rw
            - ../volumes/git/logs:/var/log/git:rw
            - ../volumes/git/data:/var/opt/git:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - PORT=443
            - IT_PW=${IT_PW}
            - OFFICE_PW=${OFFICE_PW}
            - VIRTUAL_HOST=git.<DOMAIN>
            - VIRTUAL_PORT=80
            - VIRTUAL_PROTO=http
            - CERT_NAME=default
            - GITLAB_ROOT_PASSWORD=${IT_PW}
            - GITLAB_ROOT_EMAIL=admin@ed
            - GITLAB_OMNIBUS_CONFIG = |
                nginx['enable']=true;external_url='https://git.<DOMAIN>'
                gitlab_rails['gitlab_shell_ssh_port'] = 2224
                gitlab_rails['initial_root_password'] = '${IT_PW}'
                gitlab_rails['gitlab_signup_enabled'] = false
                nginx['proxy_set_headers']={'X-Forwarded-Proto'=>'https','X-Forwarded-Ssl'=>'on'}
            - LETSENCRYPT_HOST=git.<DOMAIN>
            - LETSENCRYPT_EMAIL=<ALERT_EMAIL>

        
        
