    ope-gateway:
        build: ./ope-gateway
        image: operepo/ope-gateway
        container_name: ope-gateway
        #command:
        ports:
            - "80:80"
            #- "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            # /certs directory can be mapped if you put your certs in the volumes folder
            - ../volumes/gateway/certs:/etc/nginx/certs:rw
        env_file: .env
        environment:
            - DEFAULT_HOST=fog.<DOMAIN>

