##### Open Prison Education - Docker Environment #####
# NOTE - This file gets rebuilt, make changes to docker-compose-include.yml file
#           in individual container directories and run rebuild_compose.py 
#
# Start docker containers by running this command from the main folder:
#        docker-compose up -d
#
# Stop containers by running this command from the main folder:
#        docker-compose down
#
# START OF docker-compose.yml
version: '2'



services:

    ope-rachel:
        build: ./ope-rachel
        image: kgonyo/ope-rachel
        container_name: ope-rachel
        ports:
            - "80"
        volumes:
            # Normal mounts, using rachel app included in the container, can leave on during dev
            - ../volumes/rachel/modules:/var/www/html/modules:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - IT_PW=${IT_PW}
            - OFFICE_PW=${OFFICE_PW}
            - VIRTUAL_HOST=rachel.ed
            - VIRTUAL_PORT=80
            # Share the default cert on the gateway
            - CERT_NAME=default
            - VIRTUAL_PROTO=http
            #- HTTPS_METHOD=noredirect


    ope-dns:
        build: ./ope-dns
        image: operepo/ope-dns
        container_name: ope-dns
        cap_add:
            - NET_ADMIN
        command: -A /ed/192.168.249.181 # --log-facility=-
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        env_file: .env
        environment:
            - IP_ADDR=192.168.249.181


    ope-redis:
        build: ./ope-redis
        image: operepo/ope-redis
        container_name: ope-redis
        ports:
            - "6379:6379"
        volumes:
            - ../volumes/redis/data:/data:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env


    ope-gateway:
        build: ./ope-gateway
        image: operepo/ope-gateway
        container_name: ope-gateway
        #command:
        ports:
            - "80:80"
            #- "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            # /certs directory can be mapped if you put your certs in the volumes folder
            - ../volumes/gateway/certs:/etc/nginx/certs:rw
        env_file: .env


