##### Open Prison Education - Docker Environment #####
# NOTE - This file gets rebuilt, make changes to docker-compose-include.yml file
#           in individual container directories and run rebuild_compose.py 
#
# Start docker containers by running this command from the main folder:
#        docker-compose up -d
#
# Stop containers by running this command from the main folder:
#        docker-compose down
#
# START OF docker-compose.yml
version: '2'



services:

    ope-gateway:
        build: ./ope-gateway
        image: operepo/ope-gateway
        container_name: ope-gateway
        #command:
        ports:
            - "80:80"
            #- "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            # /certs directory can be mapped if you put your certs in the volumes folder
            - ../volumes/gateway/certs:/etc/nginx/certs:rw
        env_file: .env
        environment:
            - DEFAULT_HOST=fog.ed



    ope-gcf:
        build: ./ope-gcf
        image: operepo/ope-gcf
        container_name: ope-gcf
        ports:
            - "80"
        labels:
            - "traefik.backend=gcf"
            - "traefik.frontend.rule=Host:gcf.ed, gcflearnfree.org, gcflearnfree.ed"
            - "traefik.port=80"
            - "traefik.frontend.entryPoints=http"
        volumes:
            - ../volumes/gcf/www:/usr/share/nginx/html:ro
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - VIRTUAL_HOST=gcf.ed,gcflearnfree.org,gcflearnfree.ed
        #    - NGINX_HOST=gcf.ed
        #    - NGINX_PORT=80
        #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


    ope-fog:
        build: ./ope-fog
        image: operepo/ope-fog
        container_name: ope-fog
        #network_mode: host
        cap_add:
            #- NET_ADMIN
            #- SYS_ADMIN
            - ALL
        ports:
            - "80"
            - "443"
            #- "212:212/udp"
            #- "9098:9098"
            - "21:21"
            #- "69:69"
            - "69:69/udp"
            #- "8099:8099"
            #- "2049:2049"
            #- "2049:2049/udp"
            #- "111:111/udp"
            #- "111:111"
            #- "4045:4045/udp"
            #- "4045:4045"
            #- "34463:34463"
            #- "34463:34463/udp"
            - "7000:7020/udp"
            #- "7000:7020"
        labels:
            - fogproject="Open Source PC Imaging Server"
        volumes:
            - ../volumes/fog/images:/images:rw
            - ../volumes/fog/backup:/backup:rw
            #- ../volumes/fog/tftpboot:/tftpboot:rw
            #- ../volumes/fog/opt/fog:/opt/fog:rw
            - ../volumes/fog/mysql/data:/var/lib/mysql:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - IT_PW=${IT_PW}
            - OFFICE_PW=${OFFICE_PW}
            - VIRTUAL_HOST=fog.ed,fogserver,fogserver.ed
            - PUBLIC_IP=${PUBLIC_IP}
            #- VIRTUAL_PORT=7480
            # Share the default cert on the gateway
            - CERT_NAME=default
            #- VIRTUAL_PROTO=http
            - HTTPS_METHOD=noredirect
        


    ope-dns:
        build: ./ope-dns
        image: operepo/ope-dns
        container_name: ope-dns
        cap_add:
            - NET_ADMIN
        command: -A /ed/192.168.10.26 # --log-facility=-
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        env_file: .env
        environment:
            - IP_ADDR=192.168.10.26


