    ope-canvas-mathman:
        build: ./ope-canvas-mathman
        image: operepo/ope-canvas-mathman:release
        container_name: ope-canvas-mathman
        network_mode: <NETWORK_MODE>
        restart: always
        ports:
            - "80"
        #volumes:
        #    # Normal mounts
        depends_on:
            - ope-gateway
            - ope-dns
            - ope-redis
        env_file: .env
        environment:
            - VIRTUAL_HOST=mathman.<DOMAIN>,<CANVAS_MATHMAN_DEFAULT_DOMAIN>
            - CANVAS_MATHMAN_DEFAULT_DOMAIN=${CANVAS_MATHMAN_DEFAULT_DOMAIN}
            - VIRTUAL_PORT=80
            # Share the default cert on the gateway
            - CERT_NAME=default
            - VIRTUAL_PROTO=http
            #- HTTPS_METHOD=noredirect
            # Params for the start script
            - IS_ONLINE=${IS_ONLINE}
            - NODE_ENV=production
            # allow test/self signed certs
            - NODE_TLS_REJECT_UNAUTHORIZED=0
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - LETSENCRYPT_HOST=<CANVAS_MATHMAN_DEFAULT_DOMAIN>
            - LETSENCRYPT_EMAIL=<ALERT_EMAIL>
        links:
            # Send rce connections through the gateway
            - ope-gateway:${CANVAS_DEFAULT_DOMAIN}
            - ope-redis:redis
