    ope-canvas:
        build: ./ope-canvas
        image: operepo/ope-canvas:release
        container_name: ope-canvas
        network_mode: <NETWORK_MODE>
        restart: always
        ports:
            - "3000"
        volumes:
            # Normal mounts
            - ../volumes/canvas/tmp:/usr/src/app/tmp:rw
            - ../volumes/canvas/log:/usr/src/app/log:rw
            - ../volumes/canvas/tmpfiles:/tmp:rw
        depends_on:
            - ope-gateway
            - ope-dns
            - ope-redis
            - ope-postgresql
            - ope-canvas-rce
            - ope-canvas-mathman
        env_file: .env
        environment:
            - IT_PW=${IT_PW}
            - OFFICE_PW=${OFFICE_PW}
            - VIRTUAL_HOST=rce.<DOMAIN>,canvas.<DOMAIN>,<DOMAIN>,<CANVAS_DEFAULT_DOMAIN>
            - CANVAS_LMS_ADMIN_PASSWORD=${IT_PW}
            - CANVAS_LMS_ADMIN_EMAIL=${ADMIN_EMAIL}
            - CANVAS_LMS_ACCOUNT_NAME=${LMS_ACCOUNT_NAME}
            - CANVAS_LMS_STATS_COLLECTION="opt_out"
            - CANVAS_SECRET=${CANVAS_SECRET}
            - TIME_ZONE=${TIME_ZONE}
            - CANVAS_LOGIN_PROMPT=${CANVAS_LOGIN_PROMPT}
            - CANVAS_DEFAULT_DOMAIN=${CANVAS_DEFAULT_DOMAIN}
            - VIRTUAL_PORT=3000
            # Share the default cert on the gateway
            - CERT_NAME=<CERT_NAME>
            - VIRTUAL_PROTO=http
            #- HTTPS_METHOD=noredirect
            # Params for the start script
            - EMAIL_DELIVERY_METHOD=test
            - SMTP_ADDRESS=localhost
            - SMTP_PORT=25
            - SMTP_USER=smtp_user
            - SMTP_PASS=smtp_pass
            - IS_ONLINE=${IS_ONLINE}
            # RCE server params
            - CANVAS_ENC_SECRET=${CANVAS_ENC_SECRET}
            - CANVAS_SIGN_SECRET=${CANVAS_SIGN_SECRET}
            - CANVAS_RCE_DEFAULT_DOMAIN=${CANVAS_RCE_DEFAULT_DOMAIN}
            - NODE_TLS_REJECT_UNAUTHORIZED=0
            # Params for Mathman service
            - CANVAS_MATHMAN_DEFAULT_DOMAIN=${CANVAS_MATHMAN_DEFAULT_DOMAIN}
            - LETSENCRYPT_HOST=<CANVAS_DEFAULT_DOMAIN>
            - LETSENCRYPT_EMAIL=<ALERT_EMAIL>
        links:
            - ope-postgresql:postgresql
            - ope-redis:redis
            # Send links to rce server through the gateway
            - ope-gateway:${CANVAS_RCE_DEFAULT_DOMAIN}
            - ope-gateway:${CANVAS_MATHMAN_DEFAULT_DOMAIN}

