    ope-gcf:
        build: ./ope-gcf
        image: operepo/ope-gcf:release
        container_name: ope-gcf
        network_mode: <NETWORK_MODE>
        restart: always
        ports:
            - "80"
        #labels:
        volumes:
            - ../volumes/gcf/www:/usr/share/nginx/html:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - VIRTUAL_HOST=gcf.<DOMAIN>,gcflearnfree.org,gcflearnfree.<DOMAIN>
            - VIRTUAL_PORT=80        
            - CERT_NAME=<CERT_NAME>
            - VIRTUAL_PROTO=http
            - LETSENCRYPT_HOST=gcf.<DOMAIN>
            - LETSENCRYPT_EMAIL=<ALERT_EMAIL>


