    ope-smc:
        build: ./ope-smc
        image: ghcr.io/open-prison-education/ope-smc:release
        container_name: ope-smc
        network_mode: <NETWORK_MODE>
        restart: always
        ports:
            - "8000"
            - "9418:9418"
        volumes:
            # Normal mounts, using smc app included in the container, can leave on during dev
            - <VOLUMES_ROOT>/smc/git:/home/www-data/git:rw
            - <VOLUMES_ROOT>/smc/cache:/home/www-data/smc/web2py/applications/smc/cache:rw
            - <VOLUMES_ROOT>/smc/databases:/home/www-data/smc/web2py/applications/smc/databases:rw
            - <VOLUMES_ROOT>/smc/errors:/home/www-data/smc/web2py/applications/smc/errors:rw
            - <VOLUMES_ROOT>/smc/private:/home/www-data/smc/web2py/applications/smc/private:rw
            - <VOLUMES_ROOT>/smc/media:/home/www-data/smc/web2py/applications/smc/static/media:rw
            - <VOLUMES_ROOT>/smc/documents:/home/www-data/smc/web2py/applications/smc/static/documents:rw
            - <VOLUMES_ROOT>/smc/uploads:/home/www-data/smc/web2py/applications/smc/uploads:rw
            - <VOLUMES_ROOT>/smc/sessions:/home/www-data/smc/web2py/applications/smc/sessions:rw
            # Dev mounts, mount the whole thing from outside the container - turn this off for production servers
            #- <VOLUMES_ROOT>/smc/src:/home/www-data/smc/web2py/applications/smc:rw
            # Expose ca.crt file for other services
            - <VOLUMES_ROOT>/gateway/certs:/home/www-data/smc/web2py/applications/smc/static/certs:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - IT_PW=${IT_PW}
            - OFFICE_PW=${OFFICE_PW}
            - CANVAS_SECRET=${CANVAS_SECRET}
            - CANVAS_SERVER=https://canvas.<DOMAIN>
            - VIRTUAL_HOST=smc.<DOMAIN>,admin.<DOMAIN>,videos.<DOMAIN>,media.<DOMAIN>,<SMC_DEFAULT_DOMAIN>
            - LETSENCRYPT_HOST=<SMC_DEFAULT_DOMAIN>
            - LETSENCRYPT_EMAIL=<ALERT_EMAIL>
            - VIRTUAL_PORT=8000
            # Share the default cert on the gateway
            - CERT_NAME=<CERT_NAME>
            #- VIRTUAL_PROTO=https
            - VIRTUAL_PROTO=uwsgi
            - HTTPS_METHOD=redirect
            - IS_ONLINE=${IS_ONLINE}
        links:
            - ope-postgresql:postgresql
            # Send canvas connections through the gateway
            - ope-gateway:canvas.<DOMAIN>
            - ope-redis:redis
