    ope-dns:
        build: ./ope-dns
        image: operepo/ope-dns:release
        container_name: ope-dns
        restart: always
        network_mode: <NETWORK_MODE>
        cap_add:
            - NET_ADMIN
        command: " -A /<DOMAIN>/<IP> --txt-record=_acme-challenge.<DOMAIN>,<ACME_AUTH_CODE> <DNS_EXTRAS> " 
        # --auth-server=<DOMAIN>  - caused error on older container?
        #--log-queries 
        #--log-facility=-"
        # --log-facility=-
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        env_file: .env
        #depends_on:
        #    - ope-router
        environment:
            - IP_ADDR=<IP>
