    ope-jsbin:
        build: ./ope-jsbin
        image: operepo/ope-jsbin:release
        container_name: ope-jsbin
        network_mode: <NETWORK_MODE>
        restart: always
        ports:
            - "80"
        volumes:
            - ../volumes/jsbin/data:/data:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - PORT=80
            - JSBIN_CONFIG=/config/jsbin.json
            - IT_PW=${IT_PW}
            - OFFICE_PW=${OFFICE_PW}
            - VIRTUAL_HOST=jsbin.<DOMAIN>
            #- VIRTUAL_PORT=3000
            - CERT_NAME=<CERT_NAME>
            - VIRTUAL_PROTO=http
            - LETSENCRYPT_HOST=jsbin.<DOMAIN>
            - LETSENCRYPT_EMAIL=<ALERT_EMAIL>

        
        
