    ope-router:
        build: ./ope-router
        image: operepo/ope-router:release
        container_name: ope-router
        restart: always
        network_mode: host
        #network_mode: <NETWORK_MODE>
        #networks:
        #     - default
        #     - host_network
        privileged: true
        cap_add:
             #- NET_ADMIN
             #- SYS_ADMIN
             - ALL
        #ports:
        #    - "80"
        labels:
            desc: "Routing, kernel modules, and multicast settings"
        #volumes:
        #    - ../volumes/gcf/www:/usr/share/nginx/html:ro
        #depends_on:
        #    - ope-gateway
        #    - ope-dns
        env_file: .env
        #environment:
        #    - VIRTUAL_HOST=gcf.<DOMAIN>,gcflearnfree.org,gcflearnfree.<DOMAIN>
        #    - NGINX_HOST=gcf.<DOMAIN>
        #    - NGINX_PORT=80
        #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
