    ope-postgresql:
        build: ./ope-postgresql
        image: operepo/ope-postgresql:release
        container_name: ope-postgresql
        network_mode: <NETWORK_MODE>
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ../volumes/postgresql/data:/var/lib/postgresql/data:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=${IT_PW}
            - PGDATA=/var/lib/postgresql/data/pgdata-12.9
