    ope-kalite:
        build: ./ope-kalite
        image: operepo/ope-kalite:release
        container_name: ope-kalite
        network_mode: <NETWORK_MODE>
        restart: always
        ports:
            - "8008"
        volumes:
            - ../volumes/kalite:/root/.kalite:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - VIRTUAL_HOST=kalite.<DOMAIN>,khan.<DOMAIN>
            - LETSENCRYPT_HOST=khan.<DOMAIN>,kalite.<DOMAIN>
            - LETSENCRYPT_EMAIL=<ALERT_EMAIL>

       
