    ope-kalite:
        build: ./ope-kalite
        image: operepo/ope-kalite:release
        container_name: ope-kalite
        network_mode: <NETWORK_MODE>
        restart: always
        ports:
            - "8008"
        volumes:
            - ../volumes/kalite:/root/.kalite:rw
        depends_on:
            - ope-gateway
            - ope-dns
        env_file: .env
        environment:
            - VIRTUAL_HOST=kalite.<DOMAIN>,khan.<DOMAIN>
            - LETSENCRYPT_HOST=khan.<DOMAIN>,kalite.<DOMAIN>
            - LETSENCRYPT_EMAIL=<ALERT_EMAIL>
            - VIRTUAL_PORT=8008
            # Share the default cert on the gateway
            - CERT_NAME=<CERT_NAME>
            - VIRTUAL_PROTO=http
            #- VIRTUAL_PROTO=uwsgi
            - HTTPS_METHOD=redirect
            - IS_ONLINE=${IS_ONLINE}
       
